# Site settings
title: I Need Something to do so I Will Write
description: "Just gonna write some stuff about music, climate, technology, life, and whatever I want."
email: vosbrayden@gmail.com
baseurl: "/theoryofbrayden" # your GitHub repo name
url: "https://vosbrayden.github.io"

# Author settings
author:
  name: Brayden Vos
  email: vosbrayden@gmail.com

# Build settings
markdown: kramdown
future: true
permalink: /:year-:month-:day/:title/

# Pagination
paginate: 5
paginate_path: "/page:num"

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Include folders
include:
  - _pages

# Excluded files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - tale.gemspec
  - README.md
  - node_modules
  - vendor

# Disqus (optional)
# disqus: your-disqus-id

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X
